baseURL = 'https://site-tms--draft.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menu.main]]
  name = "PulseFrames"
  url = "/post/whatarewebstories/"

  [[menu.main]]
  name = "Case Studies"
  weight = 100
  hasChildren = true
  identifier = "stories"

[[menu.main]]
  name = "Blog"
  url = "/blog"
